// Java
package com.toufik.transactiongeneratorservice.util;

public enum Field50kPerson {
    JOHN_DOE("JOHN DOE", "1 MAIN STREET\nBRUSSELS BE"),
    ALICE_SMITH("ALICE SMITH", "22 RUE DE PARIS\nPARIS FR"),
    MARC_DUBOIS("MARC DUBOIS", "45 BAKER STREET\nLONDON UK"),
    EMILY_CLARK("EMILY CLARK", "17 ALPENWEG\nZURICH CH"),
    LUCAS_MEYER("LUCAS MEYER", "88 BROADWAY\nNEW YORK US"),
    DAVID_WILSON("DAVID WILSON", "100 OXFORD STREET\nLONDON UK"),
    SOPHIA_GARCIA("SOPHIA GARCIA", "25 GRAN VIA\nMADRID ES"),
    JAMES_BROWN("JAMES BROWN", "30 SOUTHSIDE AVE\nCHICAGO US"),
    EMMA_TAYLOR("EMMA TAYLOR", "42 QUEEN STREET\nTORONTO CA"),
    MICHAEL_LEE("MICHAEL LEE", "15 CHANGAN STREET\nBEIJING CN"),
    OLIVIA_MARTIN("OLIVIA MARTIN", "8 RUE DE LA PAIX\nLYON FR"),
    WILLIAM_ANDERSON("WILLIAM ANDERSON", "12 ELM STREET\nBOSTON US"),
    AVA_THOMAS("AVA THOMAS", "33 PARK LANE\nMANCHESTER UK"),
    BENJAMIN_HERNANDEZ("BENJAMIN HERNANDEZ", "7 AVENIDA LIBERTAD\nBARCELONA ES"),
    CHARLOTTE_WHITE("CHARLOTTE WHITE", "19 HIGH STREET\nEDINBURGH UK"),
    HENRY_SCOTT("HENRY SCOTT", "50 SUNSET BLVD\nLOS ANGELES US"),
    AMELIA_GREEN("AMELIA GREEN", "24 GARDEN SQUARE\nDUBLIN IE"),
    JACKSON_ADAMS("JACKSON ADAMS", "9 MICHIGAN AVE\nDETROIT US"),
    MIA_RODRIGUEZ("MIA RODRIGUEZ", "3 CALLE MAYOR\nSEVILLE ES"),
    LUCAS_KING("LUCAS KING", "60 RIVERSIDE DR\nNEW YORK US"),
    HARPER_BAKER("HARPER BAKER", "18 CHURCH ROAD\nLIVERPOOL UK"),
    ETHAN_CAMPBELL("ETHAN CAMPBELL", "22 MAPLE STREET\nVANCOUVER CA"),
    ABIGAIL_NELSON("ABIGAIL NELSON", "14 HILLTOP DR\nSAN FRANCISCO US"),
    ALEXANDER_CARTER("ALEXANDER CARTER", "5 OAK AVENUE\nMONTREAL CA"),
    ELLA_MITCHELL("ELLA MITCHELL", "27 VALLEY VIEW\nSYDNEY AU"),
    DANIEL_ROBERTS("DANIEL ROBERTS", "31 PINE STREET\nSEATTLE US"),
    SCARLETT_TURNER("SCARLETT TURNER", "8 THE GROVE\nMELBOURNE AU"),
    MATTHEW_PHILLIPS("MATTHEW PHILLIPS", "13 LAKESHORE DR\nCHICAGO US"),
    LILY_EVANS("LILY EVANS", "42 WILLOW WAY\nCAPE TOWN ZA"),
    JACK_COLLINS("JACK COLLINS", "19 BEACH ROAD\nMIAMI US"),
    ZOE_STEWART("ZOE STEWART", "6 MOUNTAIN VIEW\nVANCOUVER CA"),
    NATHAN_SANCHEZ("NATHAN SANCHEZ", "11 SUNSET AVENUE\nMEXICO CITY MX"),
    HANNAH_MORRIS("HANNAH MORRIS", "23 RIVER LANE\nDUBLIN IE"),
    SAMUEL_RIVERA("SAMUEL RIVERA", "16 COAST DRIVE\nSAN DIEGO US"),
    AUBREY_COOK("AUBREY COOK", "29 FOREST HILL\nTORONTO CA"),
    JOSEPH_BELL("JOSEPH BELL", "4 HARBOUR VIEW\nHONG KONG HK"),
    VICTORIA_WARD("VICTORIA WARD", "37 MEADOW STREET\nLONDON UK"),
    DAVID_MURPHY("DAVID MURPHY", "10 CLIFFSIDE DR\nBOSTON US"),
    GRACE_COOPER("GRACE COOPER", "21 HILLCREST AVE\nSYDNEY AU"),
    CHRISTOPHER_PETERSON("CHRISTOPHER PETERSON", "8 VALLEY ROAD\nAUCKLAND NZ"),
    CHLOE_REED("CHLOE REED", "15 SUNNYDALE LANE\nMELBOURNE AU"),
    ANDREW_SANDERS("ANDREW SANDERS", "12 LAKEFRONT DR\nCHICAGO US"),
    ZOEY_PRICE("ZOEY PRICE", "33 OCEAN VIEW\nSAN FRANCISCO US"),
    DYLAN_BENNETT("DYLAN BENNETT", "7 HIGHLAND AVE\nEDINBURGH UK"),
    LAYLA_HUGHES("LAYLA HUGHES", "19 BROOKSIDE RD\nDUBLIN IE"),
    RYAN_GRAY("RYAN GRAY", "24 CEDAR STREET\nVANCOUVER CA"),
    MADISON_FOSTER("MADISON FOSTER", "9 SUNSET BLVD\nLOS ANGELES US"),
    JASON_BRYANT("JASON BRYANT", "5 RIVERVIEW DR\nNEW YORK US"),
    PENELOPE_RUSSELL("PENELOPE RUSSELL", "28 PARK AVENUE\nLONDON UK");

    private final String name;
    private final String address;

    Field50kPerson(String name, String address) {
        this.name = name;
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public String getAddress() {
        return address;
    }
}